"""login id unique key drop

Revision ID: 17b07ae20ea8
Revises: bb09ab34d404
Create Date: 2024-11-08 09:08:55.482795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17b07ae20ea8'
down_revision: Union[str, None] = 'bb09ab34d404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('UQ_user_1', table_name='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('UQ_user_1', 'user', ['login_id'], unique=True)
    # ### end Alembic commands ###
