"""gpt, embedding model price table add

Revision ID: 27cd147612f1
Revises: 31c68a65ebde
Create Date: 2024-09-19 04:44:53.719319

"""
from decimal import Decimal
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '27cd147612f1'
down_revision: Union[str, None] = '31c68a65ebde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    model = op.create_table('model',
                            sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='아이디'),
                            sa.Column('name', mysql.VARCHAR(length=50), nullable=True, comment='이름'),
                            sa.Column('amount', mysql.DECIMAL(precision=34, scale=18), nullable=True, comment='금액'),
                            sa.PrimaryKeyConstraint('id'),
                            comment='모델 테이블'
                            )

    op.bulk_insert(model, [
        {
            "name": "gpt-3.5-turbo input",
            "amount": Decimal(0.0000015)
        },
        {
            "name": "gpt-3.5-turbo output",
            "amount": Decimal(0.000003)
        },
        {
            "name": "gpt-4o input",
            "amount": Decimal(0.0000025)
        },
        {
            "name": "gpt-4o output",
            "amount": Decimal(0.0000075)
        },
        {
            "name": "text-embedding-3-small",
            "amount": Decimal(0.00000001)
        },
        {
            "name": "text-embedding-3-large",
            "amount": Decimal(0.000000065)
        },
        {
            "name": "text-embedding-ada-002",
            "amount": Decimal(0.000000050)
        }
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model')
    # ### end Alembic commands ###
