"""usage_quantity table add, token cnt/amount column drop, vectordb id nullable, vectordb status add

Revision ID: 31c68a65ebde
Revises: 8b790e40df51
Create Date: 2024-09-09 07:04:28.234698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '31c68a65ebde'
down_revision: Union[str, None] = '8b790e40df51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_quantity',
                    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='아이디'),
                    sa.Column('usqty_type', mysql.VARCHAR(length=1), nullable=False,
                              comment='사용량 유형. 0:전처리,1:임베딩,2:사용자'),
                    sa.Column('type_id', mysql.INTEGER(), nullable=False, comment='유형 아이디'),
                    sa.Column('crud_type', mysql.VARCHAR(length=1), nullable=False,
                              comment='crud 유형. c:insert,u:update'),
                    sa.Column('question_token_cnt', mysql.INTEGER(), nullable=True, comment='질문 토큰 수'),
                    sa.Column('answer_token_cnt', mysql.INTEGER(), nullable=True, comment='답변 토큰 수'),
                    sa.Column('use_token_cnt', mysql.INTEGER(), nullable=True, comment='사용 토큰 수'),
                    sa.Column('use_amount', mysql.DECIMAL(precision=34, scale=18), nullable=True, comment='사용 금액'),
                    sa.Column('creation_id', mysql.INTEGER(), nullable=False, comment='생성 아이디'),
                    sa.Column('creation_dt', mysql.DATETIME(), nullable=False, comment='생성 일시'),
                    sa.PrimaryKeyConstraint('id'),
                    comment='사용량 테이블'
                    )
    op.alter_column('chatbot', 'call_path',
                    existing_type=mysql.VARCHAR(length=10),
                    comment='호출 경로. user, api',
                    existing_comment='호출 경로. user,api',
                    existing_nullable=False)
    op.alter_column('chatbot', 'vectordb_id',
                    existing_type=mysql.INTEGER(),
                    nullable=True,
                    existing_comment='벡터디비 아이디')
    op.drop_column('chatbot', 'question_token_cnt')
    op.drop_column('chatbot', 'answer_token_cnt')
    op.drop_column('chatbot', 'use_amount')
    op.drop_column('preprocessing', 'use_amount')
    op.drop_column('preprocessing', 'use_token_cnt')
    op.add_column('vectordb',
                  sa.Column('data_status', mysql.VARCHAR(length=1), nullable=False, comment='데이터 상태. Y:정상, N(삭제)'))
    op.drop_column('vectordb', 'use_token_cnt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vectordb',
                  sa.Column('use_token_cnt', mysql.INTEGER(), autoincrement=False, nullable=False, comment='사용 토큰 수'))
    op.drop_column('vectordb', 'data_status')
    op.add_column('preprocessing',
                  sa.Column('use_token_cnt', mysql.INTEGER(), autoincrement=False, nullable=True, comment='사용 토큰 수'))
    op.add_column('preprocessing',
                  sa.Column('use_amount', mysql.DECIMAL(precision=34, scale=18), nullable=True, comment='사용 금액'))
    op.add_column('chatbot',
                  sa.Column('use_amount', mysql.DECIMAL(precision=34, scale=18), nullable=True, comment='사용 금액'))
    op.add_column('chatbot',
                  sa.Column('answer_token_cnt', mysql.INTEGER(), autoincrement=False, nullable=True, comment='답변 토큰 수'))
    op.add_column('chatbot', sa.Column('question_token_cnt', mysql.INTEGER(), autoincrement=False, nullable=False,
                                       comment='질문 토큰 수'))
    op.alter_column('chatbot', 'vectordb_id',
                    existing_type=mysql.INTEGER(),
                    nullable=False,
                    existing_comment='벡터디비 아이디')
    op.alter_column('chatbot', 'call_path',
                    existing_type=mysql.VARCHAR(length=10),
                    comment='호출 경로. user,api',
                    existing_comment='호출 경로. user, api',
                    existing_nullable=False)
    op.drop_table('usage_quantity')
    # ### end Alembic commands ###
