"""screen id nullable, drop unique

Revision ID: 3adc12734225
Revises: 1966fbcc11e5
Create Date: 2024-08-30 02:41:38.845303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3adc12734225'
down_revision: Union[str, None] = '60608f6ab9ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vectordb', 'screen_id',
                    existing_type=mysql.VARCHAR(length=100),
                    nullable=True,
                    existing_comment='화면 아이디. source')
    op.drop_index('UQ_vectordb_1', table_name='vectordb')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('UQ_vectordb_1', 'vectordb', ['screen_id'], unique=True)
    op.alter_column('vectordb', 'screen_id',
                    existing_type=mysql.VARCHAR(length=100),
                    nullable=False,
                    existing_comment='화면 아이디. source')
    # ### end Alembic commands ###
