"""vectordb use_token_cnt add

Revision ID: 3c11482595e7
Revises: f981d7732746
Create Date: 2024-09-05 08:58:45.866880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3c11482595e7'
down_revision: Union[str, None] = 'f981d7732746'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vectordb', sa.Column('use_token_cnt', mysql.INTEGER(), nullable=False, comment='사용 토큰 수'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vectordb', 'use_token_cnt')
    # ### end Alembic commands ###
