"""hash_id unique key

Revision ID: 497f01bd2e8a
Revises: 9ec1787be58f
Create Date: 2024-10-27 09:34:44.450584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '497f01bd2e8a'
down_revision: Union[str, None] = '9ec1787be58f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vectordb', sa.Column('hash_id', mysql.VARCHAR(length=100), nullable=False, comment='해시 아이디'))
    op.create_unique_constraint('UQ_vectordb_1', 'vectordb', ['hash_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('UQ_vectordb_1', 'vectordb', type_='unique')
    op.drop_column('vectordb', 'hash_id')
    # ### end Alembic commands ###
