"""chatbot vectordb table vectordb_id nullable

Revision ID: 4b0243608cd7
Revises: f2bb797eecbe
Create Date: 2024-11-18 02:37:13.008649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4b0243608cd7'
down_revision: Union[str, None] = 'f2bb797eecbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chatbot_vectordb', 'id',
                    existing_type=mysql.INTEGER(),
                    comment='아이디',
                    existing_nullable=False,
                    autoincrement=True)
    op.alter_column('chatbot_vectordb', 'vectordb_id',
                    existing_type=mysql.INTEGER(),
                    nullable=True,
                    existing_comment='벡터디비 아이디')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chatbot_vectordb', 'vectordb_id',
                    existing_type=mysql.INTEGER(),
                    nullable=False,
                    existing_comment='벡터디비 아이디')
    op.alter_column('chatbot_vectordb', 'id',
                    existing_type=mysql.INTEGER(),
                    comment=None,
                    existing_comment='아이디',
                    existing_nullable=False,
                    autoincrement=True)
    # ### end Alembic commands ###
