"""hash_id column size 32 to 36

Revision ID: 59cd25e39e7e
Revises: d26764cc58a1
Create Date: 2024-10-29 02:34:05.077613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '59cd25e39e7e'
down_revision: Union[str, None] = 'd26764cc58a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vectordb', 'hash_id',
                    existing_type=mysql.VARCHAR(length=32),
                    type_=mysql.VARCHAR(length=36),
                    existing_comment='해시 아이디',
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vectordb', 'hash_id',
                    existing_type=mysql.VARCHAR(length=36),
                    type_=mysql.VARCHAR(length=32),
                    existing_comment='해시 아이디',
                    existing_nullable=False)
    # ### end Alembic commands ###
