"""user/admin password length modify

Revision ID: 60608f6ab9ce
Revises: ebc9c9e8ab13
Create Date: 2024-08-28 06:05:33.130161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '60608f6ab9ce'
down_revision: Union[str, None] = 'ebc9c9e8ab13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bo_user', 'password',
                    existing_type=mysql.VARCHAR(length=50),
                    type_=mysql.VARCHAR(length=255),
                    existing_comment='비밀번호',
                    existing_nullable=False)
    op.alter_column('user', 'password',
                    existing_type=mysql.VARCHAR(length=50),
                    type_=mysql.VARCHAR(length=255),
                    existing_comment='비밀번호',
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
                    existing_type=mysql.VARCHAR(length=255),
                    type_=mysql.VARCHAR(length=50),
                    existing_comment='비밀번호',
                    existing_nullable=False)
    op.alter_column('bo_user', 'password',
                    existing_type=mysql.VARCHAR(length=255),
                    type_=mysql.VARCHAR(length=50),
                    existing_comment='비밀번호',
                    existing_nullable=False)
    # ### end Alembic commands ###
