"""preprocessing image_path add

Revision ID: 8b790e40df51
Revises: 3c11482595e7
Create Date: 2024-09-06 06:42:48.222738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8b790e40df51'
down_revision: Union[str, None] = '3c11482595e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preprocessing', sa.Column('image_path', mysql.VARCHAR(length=255), nullable=True, comment='이미지 경로'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preprocessing', 'image_path')
    # ### end Alembic commands ###
