"""preprocessing pattern nullable

Revision ID: 8c9519b25170
Revises: d495ad7efac1
Create Date: 2024-10-15 07:23:55.138154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8c9519b25170'
down_revision: Union[str, None] = 'd495ad7efac1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('preprocessing', 'preprocessing_pattern',
                    existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
                    nullable=True,
                    existing_comment='전처리 패턴')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('preprocessing', 'preprocessing_pattern',
                    existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
                    nullable=False,
                    existing_comment='전처리 패턴')
    # ### end Alembic commands ###
