"""hospital_code, login id unique key

Revision ID: 9ec1787be58f
Revises: 8c9519b25170
Create Date: 2024-10-27 09:20:21.614118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9ec1787be58f'
down_revision: Union[str, None] = '8c9519b25170'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hospital_code', mysql.VARCHAR(length=10), nullable=False, comment='병원 코드'))
    op.create_unique_constraint('UQ_user_2', 'user', ['hospital_code', 'login_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('UQ_user_2', 'user', type_='unique')
    op.drop_column('user', 'hospital_code')
    # ### end Alembic commands ###
