"""chatbot user_id nullable

Revision ID: bcd630441dc5
Revises: 27cd147612f1
Create Date: 2024-09-19 06:46:50.800257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bcd630441dc5'
down_revision: Union[str, None] = '27cd147612f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chatbot', 'user_id',
                    existing_type=mysql.INTEGER(),
                    nullable=True,
                    existing_comment='사용자 아아디')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chatbot', 'user_id',
                    existing_type=mysql.INTEGER(),
                    nullable=False,
                    existing_comment='사용자 아아디')
    # ### end Alembic commands ###
