"""bo_answer base answer init

Revision ID: cd399c60dc8f
Revises: bcd630441dc5
Create Date: 2024-09-23 02:30:15.096743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from src.core import utils

# revision identifiers, used by Alembic.
revision: str = 'cd399c60dc8f'
down_revision: Union[str, None] = 'bcd630441dc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bo_answer = sa.table(
        'bo_answer',
        sa.column('answer_content', mysql.TEXT()),
        sa.column('creation_id', mysql.INTEGER()),
        sa.column('update_id', mysql.INTEGER()),
        sa.column('creation_dt', mysql.DATETIME()),
        sa.column('update_dt', mysql.DATETIME()),
    )

    op.bulk_insert(bo_answer, [
        {
            "answer_content": "확인할 만한 답변을 찾지 못하였습니다.",
            "creation_id": 1,
            "update_id": 1,
            "creation_dt": utils.now(),
            "update_dt": utils.now()
        }
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bo_answer = sa.table(
        'bo_answer',
        sa.column('answer_content', mysql.TEXT())
    )
    stmt = (
        sa.delete(bo_answer)
    )
    op.execute(stmt)
    # ### end Alembic commands ###
