"""add hash_id

Revision ID: d26764cc58a1
Revises: 497f01bd2e8a
Create Date: 2024-10-28 02:13:50.742910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd26764cc58a1'
down_revision: Union[str, None] = '497f01bd2e8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vectordb', 'hash_id',
                    existing_type=mysql.VARCHAR(length=100),
                    type_=mysql.VARCHAR(length=32),
                    existing_comment='해시 아이디',
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vectordb', 'hash_id',
                    existing_type=mysql.VARCHAR(length=32),
                    type_=mysql.VARCHAR(length=100),
                    existing_comment='해시 아이디',
                    existing_nullable=False)
    # ### end Alembic commands ###
