"""init

Revision ID: ebc9c9e8ab13
Revises: 
Create Date: 2024-08-28 14:22:09.545093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ebc9c9e8ab13'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bo_answer',
                    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='아이디'),
                    sa.Column('answer_content', mysql.TEXT(), nullable=True, comment='답변 내용'),
                    sa.Column('creation_id', mysql.INTEGER(), nullable=False, comment='생성 아이디'),
                    sa.Column('update_id', mysql.INTEGER(), nullable=False, comment='갱신 아이디'),
                    sa.Column('creation_dt', mysql.DATETIME(), nullable=False, comment='생성 일시'),
                    sa.Column('update_dt', mysql.DATETIME(), nullable=False, comment='갱신 일시'),
                    sa.PrimaryKeyConstraint('id'),
                    comment='백오피스 답변관리 테이블'
                    )
    op.create_table('bo_auth_menu',
                    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='아이디'),
                    sa.Column('upper_menu_name', mysql.VARCHAR(length=50), nullable=False, comment='상위 메뉴 이름'),
                    sa.Column('lower_menu_name', mysql.VARCHAR(length=50), nullable=False, comment='하위 메뉴 이름'),
                    sa.Column('creation_id', mysql.INTEGER(), nullable=False, comment='생성 아이디'),
                    sa.Column('update_id', mysql.INTEGER(), nullable=False, comment='갱신 아이디'),
                    sa.Column('creation_dt', mysql.DATETIME(), nullable=False, comment='생성 일시'),
                    sa.Column('update_dt', mysql.DATETIME(), nullable=False, comment='갱신 일시'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('lower_menu_name', name='UQ_bo_auth_menu_1'),
                    comment='백오피스 권한 메뉴 테이블'
                    )
    op.create_table('bo_user',
                    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='아이디'),
                    sa.Column('login_id', mysql.VARCHAR(length=50), nullable=False, comment='로그인 아이디'),
                    sa.Column('password', mysql.VARCHAR(length=50), nullable=False, comment='비밀번호'),
                    sa.Column('name', mysql.VARCHAR(length=50), nullable=True, comment='이름'),
                    sa.Column('dept_name', mysql.VARCHAR(length=50), nullable=True, comment='부서 이름'),
                    sa.Column('tel_no', mysql.VARCHAR(length=20), nullable=True, comment='전화 번호'),
                    sa.Column('auth_menu_list', mysql.VARCHAR(length=255), nullable=True, comment='권한 메뉴 리스트'),
                    sa.Column('login_token', mysql.VARCHAR(length=500), nullable=True, comment='로그인 토큰'),
                    sa.Column('creation_id', mysql.INTEGER(), nullable=False, comment='생성 아이디'),
                    sa.Column('update_id', mysql.INTEGER(), nullable=False, comment='갱신 아이디'),
                    sa.Column('creation_dt', mysql.DATETIME(), nullable=False, comment='생성 일시'),
                    sa.Column('update_dt', mysql.DATETIME(), nullable=False, comment='갱신 일시'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('login_id', name='UQ_user_1'),
                    comment='백오피스 사용자 테이블'
                    )
    op.create_table('user',
                    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='아이디'),
                    sa.Column('login_id', mysql.VARCHAR(length=50), nullable=False, comment='로그인 아이디'),
                    sa.Column('password', mysql.VARCHAR(length=50), nullable=False, comment='비밀번호'),
                    sa.Column('name', mysql.VARCHAR(length=50), nullable=True, comment='이름'),
                    sa.Column('hospital_name', mysql.VARCHAR(length=50), nullable=True, comment='병원 이름'),
                    sa.Column('dept_name', mysql.VARCHAR(length=50), nullable=True, comment='부서 이름'),
                    sa.Column('login_token', mysql.VARCHAR(length=500), nullable=True, comment='로그인 토큰'),
                    sa.Column('creation_id', mysql.INTEGER(), nullable=False, comment='생성 아이디'),
                    sa.Column('update_id', mysql.INTEGER(), nullable=False, comment='갱신 아이디'),
                    sa.Column('creation_dt', mysql.DATETIME(), nullable=False, comment='생성 일시'),
                    sa.Column('update_dt', mysql.DATETIME(), nullable=False, comment='갱신 일시'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('login_id', name='UQ_user_1'),
                    comment='사용자 테이블'
                    )
    op.create_table('vectordb',
                    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='아이디'),
                    sa.Column('screen_id', mysql.VARCHAR(length=100), nullable=False, comment='화면 아이디. source'),
                    sa.Column('manual_name', mysql.VARCHAR(length=100), nullable=False, comment='설명서 이름'),
                    sa.Column('manual_path', mysql.VARCHAR(length=255), nullable=False, comment='설명서 경로'),
                    sa.Column('subject', mysql.VARCHAR(length=255), nullable=False, comment='주제'),
                    sa.Column('content', mysql.TEXT(), nullable=False, comment='내용'),
                    sa.Column('image_path', mysql.VARCHAR(length=255), nullable=True, comment='이미지 경로'),
                    sa.Column('creation_id', mysql.INTEGER(), nullable=False, comment='생성 아이디'),
                    sa.Column('update_id', mysql.INTEGER(), nullable=False, comment='갱신 아이디'),
                    sa.Column('creation_dt', mysql.DATETIME(), nullable=False, comment='생성 일시'),
                    sa.Column('update_dt', mysql.DATETIME(), nullable=False, comment='갱신 일시'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('screen_id', name='UQ_vectordb_1'),
                    comment='벡터디비 테이블'
                    )
    op.create_table('chatbot',
                    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='아이디'),
                    sa.Column('user_id', mysql.INTEGER(), nullable=False, comment='사용자 아아디'),
                    sa.Column('call_path', mysql.VARCHAR(length=10), nullable=False, comment='호출 경로. user,api'),
                    sa.Column('vectordb_id', mysql.INTEGER(), nullable=False, comment='벡터디비 아이디'),
                    sa.Column('question_content', mysql.TEXT(), nullable=False, comment='질문 내용'),
                    sa.Column('question_token_cnt', mysql.INTEGER(), nullable=False, comment='질문 토큰 수'),
                    sa.Column('answer_content', mysql.TEXT(), nullable=True, comment='답변 내용'),
                    sa.Column('answer_token_cnt', mysql.INTEGER(), nullable=True, comment='답변 토큰 수'),
                    sa.Column('use_amount', mysql.DECIMAL(precision=34, scale=18), nullable=True, comment='사용 금액'),
                    sa.Column('dgstfn', mysql.DECIMAL(precision=2, scale=1), nullable=True, comment='만족도'),
                    sa.Column('creation_id', mysql.INTEGER(), nullable=False, comment='생성 아이디'),
                    sa.Column('update_id', mysql.INTEGER(), nullable=False, comment='갱신 아이디'),
                    sa.Column('creation_dt', mysql.DATETIME(), nullable=False, comment='생성 일시'),
                    sa.Column('update_dt', mysql.DATETIME(), nullable=False, comment='갱신 일시'),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
                    sa.ForeignKeyConstraint(['vectordb_id'], ['vectordb.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
                    sa.PrimaryKeyConstraint('id'),
                    comment='챗봇 테이블'
                    )
    op.create_table('preprocessing',
                    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='아이디'),
                    sa.Column('preprocessing_pattern', mysql.VARCHAR(length=50), nullable=False, comment='전처리 패턴'),
                    sa.Column('manual_name', mysql.VARCHAR(length=100), nullable=False, comment='설명서 이름'),
                    sa.Column('prompt_content', mysql.TEXT(), nullable=True, comment='프롬프트 내용'),
                    sa.Column('screen_id', mysql.VARCHAR(length=100), nullable=True, comment='화면 아이디'),
                    sa.Column('subject', mysql.VARCHAR(length=255), nullable=True, comment='주제'),
                    sa.Column('content', mysql.TEXT(), nullable=True, comment='내용'),
                    sa.Column('use_token_cnt', mysql.INTEGER(), nullable=True, comment='사용 토큰 수'),
                    sa.Column('use_amount', mysql.DECIMAL(precision=34, scale=18), nullable=True, comment='사용 금액'),
                    sa.Column('creation_id', mysql.INTEGER(), nullable=False, comment='생성 아이디'),
                    sa.Column('creation_dt', mysql.DATETIME(), nullable=False, comment='생성 일시'),
                    sa.Column('update_dt', mysql.DATETIME(), nullable=False, comment='갱신 일시'),
                    sa.ForeignKeyConstraint(['creation_id'], ['bo_user.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
                    sa.PrimaryKeyConstraint('id'),
                    comment='전처리 테이블'
                    )
    op.create_table('report',
                    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='아이디'),
                    sa.Column('chatbot_id', mysql.INTEGER(), nullable=False, comment='챗봇 아이디'),
                    sa.Column('report_content', mysql.TEXT(), nullable=False, comment='보고 내용'),
                    sa.Column('creation_id', mysql.INTEGER(), nullable=False, comment='생성 아이디'),
                    sa.Column('creation_dt', mysql.DATETIME(), nullable=False, comment='생성 일시'),
                    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbot.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
                    sa.PrimaryKeyConstraint('id'),
                    comment='사용자 리포트 테이블'
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    op.drop_table('preprocessing')
    op.drop_table('chatbot')
    op.drop_table('vectordb')
    op.drop_table('user')
    op.drop_table('bo_user')
    op.drop_table('bo_auth_menu')
    op.drop_table('bo_answer')
    # ### end Alembic commands ###
