"""chatbot, vectordb 사이 중간 테이블 생성

Revision ID: f2bb797eecbe
Revises: 17b07ae20ea8
Create Date: 2024-11-15 06:03:36.924567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f2bb797eecbe'
down_revision: Union[str, None] = '17b07ae20ea8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbot_vectordb',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chatbot_id', mysql.INTEGER(), nullable=False, comment='챗봇 아이디'),
    sa.Column('vectordb_id', mysql.INTEGER(), nullable=False, comment='벡터디비 아이디'),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbot.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vectordb_id'], ['vectordb.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chatbot_vectordb')
    # ### end Alembic commands ###
