"""vectordb subject nullable

Revision ID: f981d7732746
Revises: b63cbaeadefb
Create Date: 2024-09-05 02:09:18.705183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f981d7732746'
down_revision: Union[str, None] = 'b63cbaeadefb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vectordb', 'subject',
                    existing_type=mysql.VARCHAR(length=255),
                    nullable=True,
                    existing_comment='주제')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vectordb', 'subject',
                    existing_type=mysql.VARCHAR(length=255),
                    nullable=False,
                    existing_comment='주제')
    # ### end Alembic commands ###
